# ----------------------- #
#      Jekyll Configs     #
# ----------------------- #
titlecase: true
markdown: kramdown
encoding: utf-8
incremental: true
# limit_posts: 0
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
gems:
  - fastimage
  - jekyll-archives
  - jekyll-crosspost-to-medium
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-time-to-read
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-typogrify
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - nokogiri
  - octopress-date-format
exclude:
  # Ruby & Gems
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  # Gulp
  - gulpfile.js
  - package.json
  # Content
  - README.md
  # Caches
  - node_modules
  - .cache
  - .sass-cache
  # Git
  - .gitignore
  # Docker
  - docker-compose.yml

# Project Structure
destination: _site
plugins_dir: _plugins
collections:
  posts:
    output: true
    permalink: /notebook/:title/
  links:
    output: true
    permalink: /notebook/links/:title/
defaults:
  -
    scope:
      path: ""
    values:
      image: /i/og-logo.png
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      feed: true
      is_post: true
      layout: post
  -
    scope:
      path: ""
      type: links
    values:
      feed: true
      layout: link

# ----------------------- #
#      Site Configs       #
# ----------------------- #

url: https://www.aaron-gustafson.com
simple_search: "https://www.google.com/search"

# SEO
lang: en_US
title: Aaron Gustafson
subtitle: Web Design Author, Evangelist, Practitioner, and Teacher
author:
  name: Aaron Gustafson
  uri: https://www.aaron-gustafson.com
  twitter: AaronGustafson
  googleplus: AaronGustafson
description: Hi there. My name is Aaron Gustafson and I work on the web.
twitter:
  username: AaronGustafson
facebook:
  admins: 100002880350996
logo: /i/og-logo.png
social:
  name: Aaron Gustafson
  links:
    - https://twitter.com/aarongustafson
    - https://www.facebook.com/aaronmgustafson
    - https://github.com/aarongustafson
    - https://plus.google.com/+AaronGustafson
    - https://www.linkedin.com/in/aarongustafson
    - http://lanyrd.com/profile/aarongustafson
    - http://www.slideshare.net/AaronGustafson/
    - http://instagram.com/AaronGustafson
    - http://speakerrate.com/speakers/266-aaron-gustafson
    - https://www.flickr.com/photos/aarongustafson

date_format: "%d %B %Y"
excerpt_separator: "<!-- more -->"

# URLs
root: /
blog_index_dir: /notebook/
permalink: /notebook/:title/
code_dir: /downloads/code

# RSS / Email (optional) subscription links (change if using something like Feedburner)
feeds:
  - title: "Posts and Links From the Notebook of "
    atom: "/feeds/all.xml"
    json: "/feeds/all.json"
  - title: "Posts From the Notebook of "
    atom: "/feeds/latest-posts.xml"
    json: "/feeds/latest-posts.json"
  - title: "Links From the Notebook of "
    atom: "/feeds/latest-links.xml"
    json: "/feeds/latest-links.json"

# Navigation
navigation:
  - text: <b class="hidden">A Bit </b>About<b class="hidden"> Me</b>
    url: /about/
  - text: <b class="hidden">Entries in My </b>Notebook
    url: /notebook/
  - text: <b class="hidden">A List of My </b>Speaking<b class="hidden"> Engagements</b>
    url: /speaking-engagements/
  - text: <b class="hidden">A List of My </b>Publications
    url: /publications/
  - text: <b class="hidden">Links to </b>Interviews<b class="hidden"> Iâ€™ve Given</b>
    url: /appearances/
  - text: <b class="hidden">The Requisite </b>Contact<b class="hidden"> Form</b>
    url: /contact/

# Pagination
pagination:
  enabled: true
  debug: false
  per_page: 10
  permalink: '/pg-:num/'
  title: ', Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Archives
jekyll-archives:
  enabled: tags
  layout: 'tag.html'
  permalinks:
    tag: '/notebook/tags/:name/'
  tag_title_prefix: 'Browse By Tag:'

# Asides
default_asides: [asides/recent_posts.html]
blog_index_asides: [asides/about.html,asides/networks.html,asides/recent_links.html]
post_asides: [asides/about.html,asides/events.html]
page_asides: [asides/about.html,asides/networks.html,asides/events.html]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Tagging
tag_page_layout: tag
tag_page_dir: /notebook/tags/

# Open Graph
og:
  image: /i/og-logo.png
  type: website

# Disqus Comments
disqus_short_name: aarongustafson
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: "UA-176472-5"

# Google Tag Manager
google_tag_manager_id: "GTM-P3MJZJ"

# Github repo path
github:
  repo: aarongustafson/aarongustafson.github.io
  branch: master
repo_url: "https://github.com/aarongustafson/aarongustafson.github.io/tree/master/"

# Gists
gist_tag:
  cache: .cache/gists

# Crosspost to Medium
jekyll-crosspost_to_medium:
  enabled: true
  cache: .cache
  status: draft
  license: cc-40-by-sa
  text: '<p><i>This post originally appeared <a href="{{ url }}" rel="canonical">on my blog</a>.</i></p>'

# Crossposts
crosspost_caches:
  Medium: ./.cache/medium_crossposted.yml
  Codementor: ./.cache/codementor_crossposted.yml

# Adaptive Images Config
adaptive_image:
  cache: 2592000
  srcset: 
    - 1920
    - 600
    - 320
  sizes:
    - 100vw

# AMP
#ampdir: amp
#amp_gists:
#  layout: responsive
#  width: 320
#  height: 240

webmentions:
  # debug: true
  # pause_lookups: true
  username: aaron-gustafson.com
  cache_bad_uris_for: 7 # in days
  legacy_domains:
    - http://aaron-gustafson.com
    - http://www.aaron-gustafson.com
  js:
    uglify: false
    destination: _javascript/post
    deploy: false
  templates:
    likes: _includes/webmentions/likes.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html
  throttle_lookups:
    last_month: daily
    last_year: weekly
    older: every 2 months
  collections:
    - links