# ----------------------- #
#      Site Configs       #
# ----------------------- #

url: https://www.aaron-gustafson.com
title: "Aaron Gustafson"
subtitle: "Web Design Author, Evangelist, Practitioner, and Teacher"
author: "Aaron Gustafson"
simple_search: "https://www.google.com/search"
description: "Hi there. My name is Aaron Gustafson and I work on the web."

date_format: "%d %B %Y"
excerpt_separator: "<!-- more -->"

# URLs
root: /
blog_index_dir: /notebook/
permalink: /notebook/:title/
code_dir: /downloads/code

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: "/atom.xml"
subscribe_rss_posts: "/atom-latest-posts.xml"
subscribe_rss_links: "/atom-latest-links.xml"
subscribe_email:
# RSS feeds can list your email address if you like
email:

# Navigation
navigation:
  - text: <b class="hidden">A Bit </b>About<b class="hidden"> Me</b>
    url: /about/
  - text: <b class="hidden">Entries in My </b>Notebook
    url: /notebook/
  - text: <b class="hidden">A List of My </b>Speaking<b class="hidden"> Engagements</b>
    url: /speaking-engagements/
  - text: <b class="hidden">A List of My </b>Publications
    url: /publications/
  - text: <b class="hidden">Links to </b>Interviews<b class="hidden"> Iâ€™ve Given</b>
    url: /appearances/
  - text: <b class="hidden">The Requisite </b>Contact<b class="hidden"> Form</b>
    url: /contact/

# Pagination
#notebook_paginate: 10
#notebook_pagination_dir: "notebook"
#notebook_paginate_path: "notebook/pg-:num/"
#linkblog_paginate: 10
#linkblog_pagination_dir: "notebook/links"
#linkblog_paginate_path: "notebook/links/pg-:num/"
pagination:
  enabled: true
  per_page: 10
  permalink: 'pg-:num/'
  title: ', Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Asides
default_asides: [asides/recent_posts.html]
blog_index_asides: [asides/about.html,asides/networks.html,asides/recent_links.html]
post_asides: [asides/about.html,asides/events.html]
page_asides: [asides/about.html,asides/networks.html,asides/events.html]

# ----------------------- #
#      Jekyll Configs     #
# ----------------------- #
titlecase: true
markdown: kramdown
encoding: utf-8
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
gems:
  - fastimage
  - jekyll-crosspost-to-medium
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-time-to-read
  - jekyll-seo-tag
  - jekyll-typogrify
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - nokogiri
  - octopress-date-format
exclude:
  # Ruby & Gems
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  # Gulp
  - gulpfile.js
  - package.json
  # Content
  - README.md
  # Caches
  - node_modules
  - .cache
  - .sass-cache
  # Git
  - .gitignore
  # Docker
  - docker-compose.yml

# Project Structure
destination: _site
plugins_dir: _plugins
collections:
  posts:
    output: true
    permalink: /notebook/:title/
  links:
    output: true
    permalink: /notebook/:collection/:title/
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: links
    values:
      layout: link

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Tagging
tag_page_layout: tag
tag_page_dir: /notebook/tags

# Open Graph
og:
  image: /i/og-logo.png
  type: website

# Disqus Comments
disqus_short_name: aarongustafson
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: "UA-176472-5"

# Google Tag Manager
google_tag_manager_id: "GTM-P3MJZJ"

# Github repo path
repo_url: "https://github.com/aarongustafson/aarongustafson.github.io/tree/source/source/"

# Gists
gist_tag:
  cache: .cache/gists

# Crosspost to Medium
jekyll-crosspost_to_medium:
  enabled: true
  cache: .cache
  status: draft
  license: cc-40-by-sa
  text: '<p><i>This post originally appeared <a href=\"#{url}\" rel=\"canonical\">on my blog</a>.</i></p>'

# Crossposts
crosspost_caches:
  Medium: ./.cache/medium_crossposted.yml

# Adaptive Images Config
adaptive_image:
  cache: 2592000
  srcset: 
    - 1920
    - 600
    - 320
  sizes:
    - 100vw

# AMP
ampdir: amp